import type { Metadata } from "next";
import SidebarMenu from "../../components/SidebarMenu";


export const metadata: Metadata = {
  title: "Dashboard - GolpeAI",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen">
      <SidebarMenu />
      <main className="flex-1 ml-72 p-6">{children}</main>
    </div>
  )
}

